//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 10/6/2011 9:44:14 AM
namespace SQLPassBrowser.OratorModelNS
{
    
    /// <summary>
    /// There are no comments for OratorEntities in the schema.
    /// </summary>
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    public partial class OratorEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new OratorEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public OratorEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("OratorModelNS", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("SQLPassBrowser.OratorModelNS", typeName.Substring(13)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("SQLPassBrowser.OratorModelNS", global::System.StringComparison.Ordinal))
            {
                return string.Concat("OratorModelNS.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Events in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Event> Events
        {
            get
            {
                if ((this._Events == null))
                {
                    this._Events = base.CreateQuery<Event>("Events");
                }
                return this._Events;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Event> _Events;
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Session> Sessions
        {
            get
            {
                if ((this._Sessions == null))
                {
                    this._Sessions = base.CreateQuery<Session>("Sessions");
                }
                return this._Sessions;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Session> _Sessions;
        /// <summary>
        /// There are no comments for SessionSpeakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SessionSpeaker> SessionSpeakers
        {
            get
            {
                if ((this._SessionSpeakers == null))
                {
                    this._SessionSpeakers = base.CreateQuery<SessionSpeaker>("SessionSpeakers");
                }
                return this._SessionSpeakers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SessionSpeaker> _SessionSpeakers;
        /// <summary>
        /// There are no comments for SessionFiles in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SessionFile> SessionFiles
        {
            get
            {
                if ((this._SessionFiles == null))
                {
                    this._SessionFiles = base.CreateQuery<SessionFile>("SessionFiles");
                }
                return this._SessionFiles;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SessionFile> _SessionFiles;
        /// <summary>
        /// There are no comments for Events in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEvents(Event @event)
        {
            base.AddObject("Events", @event);
        }
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSessions(Session session)
        {
            base.AddObject("Sessions", session);
        }
        /// <summary>
        /// There are no comments for SessionSpeakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSessionSpeakers(SessionSpeaker sessionSpeaker)
        {
            base.AddObject("SessionSpeakers", sessionSpeaker);
        }
        /// <summary>
        /// There are no comments for SessionFiles in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSessionFiles(SessionFile sessionFile)
        {
            base.AddObject("SessionFiles", sessionFile);
        }
    }
    /// <summary>
    /// There are no comments for OratorModelNS.Event in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EventID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Events")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("EventID")]
    public partial class Event : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Event object.
        /// </summary>
        /// <param name="eventID">Initial value of EventID.</param>
        /// <param name="eventName">Initial value of EventName.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Event CreateEvent(int eventID, string eventName)
        {
            Event @event = new Event();
            @event.EventID = eventID;
            @event.EventName = eventName;
            return @event;
        }
        /// <summary>
        /// There are no comments for Property EventID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int EventID
        {
            get
            {
                return this._EventID;
            }
            set
            {
                this.OnEventIDChanging(value);
                this._EventID = value;
                this.OnEventIDChanged();
                this.OnPropertyChanged("EventID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _EventID;
        partial void OnEventIDChanging(int value);
        partial void OnEventIDChanged();
        /// <summary>
        /// There are no comments for Property EventName in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EventName
        {
            get
            {
                return this._EventName;
            }
            set
            {
                this.OnEventNameChanging(value);
                this._EventName = value;
                this.OnEventNameChanged();
                this.OnPropertyChanged("EventName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EventName;
        partial void OnEventNameChanging(string value);
        partial void OnEventNameChanged();
        /// <summary>
        /// There are no comments for Property EventURL in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EventURL
        {
            get
            {
                return this._EventURL;
            }
            set
            {
                this.OnEventURLChanging(value);
                this._EventURL = value;
                this.OnEventURLChanged();
                this.OnPropertyChanged("EventURL");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EventURL;
        partial void OnEventURLChanging(string value);
        partial void OnEventURLChanged();
        /// <summary>
        /// There are no comments for Property EventStartDate in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> EventStartDate
        {
            get
            {
                return this._EventStartDate;
            }
            set
            {
                this.OnEventStartDateChanging(value);
                this._EventStartDate = value;
                this.OnEventStartDateChanged();
                this.OnPropertyChanged("EventStartDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _EventStartDate;
        partial void OnEventStartDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnEventStartDateChanged();
        /// <summary>
        /// There are no comments for Property EventEndDate in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> EventEndDate
        {
            get
            {
                return this._EventEndDate;
            }
            set
            {
                this.OnEventEndDateChanging(value);
                this._EventEndDate = value;
                this.OnEventEndDateChanged();
                this.OnPropertyChanged("EventEndDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _EventEndDate;
        partial void OnEventEndDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnEventEndDateChanged();
        /// <summary>
        /// There are no comments for PASS_OData_Orator_Session in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Session> PASS_OData_Orator_Session
        {
            get
            {
                return this._PASS_OData_Orator_Session;
            }
            set
            {
                this._PASS_OData_Orator_Session = value;
                this.OnPropertyChanged("PASS_OData_Orator_Session");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Session> _PASS_OData_Orator_Session = new global::System.Data.Services.Client.DataServiceCollection<Session>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for PASS_OData_Orator_SessionSpeaker in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SessionSpeaker> PASS_OData_Orator_SessionSpeaker
        {
            get
            {
                return this._PASS_OData_Orator_SessionSpeaker;
            }
            set
            {
                this._PASS_OData_Orator_SessionSpeaker = value;
                this.OnPropertyChanged("PASS_OData_Orator_SessionSpeaker");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SessionSpeaker> _PASS_OData_Orator_SessionSpeaker = new global::System.Data.Services.Client.DataServiceCollection<SessionSpeaker>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for PASS_OData_Orator_SessionFile in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SessionFile> PASS_OData_Orator_SessionFile
        {
            get
            {
                return this._PASS_OData_Orator_SessionFile;
            }
            set
            {
                this._PASS_OData_Orator_SessionFile = value;
                this.OnPropertyChanged("PASS_OData_Orator_SessionFile");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SessionFile> _PASS_OData_Orator_SessionFile = new global::System.Data.Services.Client.DataServiceCollection<SessionFile>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OratorModelNS.Session in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SessionID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Sessions")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SessionID")]
    public partial class Session : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Session object.
        /// </summary>
        /// <param name="eventID">Initial value of EventID.</param>
        /// <param name="sessionID">Initial value of SessionID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Session CreateSession(int eventID, int sessionID)
        {
            Session session = new Session();
            session.EventID = eventID;
            session.SessionID = sessionID;
            return session;
        }
        /// <summary>
        /// There are no comments for Property EventID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int EventID
        {
            get
            {
                return this._EventID;
            }
            set
            {
                this.OnEventIDChanging(value);
                this._EventID = value;
                this.OnEventIDChanged();
                this.OnPropertyChanged("EventID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _EventID;
        partial void OnEventIDChanging(int value);
        partial void OnEventIDChanged();
        /// <summary>
        /// There are no comments for Property SessionID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SessionID
        {
            get
            {
                return this._SessionID;
            }
            set
            {
                this.OnSessionIDChanging(value);
                this._SessionID = value;
                this.OnSessionIDChanged();
                this.OnPropertyChanged("SessionID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SessionID;
        partial void OnSessionIDChanging(int value);
        partial void OnSessionIDChanged();
        /// <summary>
        /// There are no comments for Property SessionName in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SessionName
        {
            get
            {
                return this._SessionName;
            }
            set
            {
                this.OnSessionNameChanging(value);
                this._SessionName = value;
                this.OnSessionNameChanged();
                this.OnPropertyChanged("SessionName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SessionName;
        partial void OnSessionNameChanging(string value);
        partial void OnSessionNameChanged();
        /// <summary>
        /// There are no comments for Property SessionDescription in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SessionDescription
        {
            get
            {
                return this._SessionDescription;
            }
            set
            {
                this.OnSessionDescriptionChanging(value);
                this._SessionDescription = value;
                this.OnSessionDescriptionChanged();
                this.OnPropertyChanged("SessionDescription");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SessionDescription;
        partial void OnSessionDescriptionChanging(string value);
        partial void OnSessionDescriptionChanged();
        /// <summary>
        /// There are no comments for Property SessionDateTimeStart in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> SessionDateTimeStart
        {
            get
            {
                return this._SessionDateTimeStart;
            }
            set
            {
                this.OnSessionDateTimeStartChanging(value);
                this._SessionDateTimeStart = value;
                this.OnSessionDateTimeStartChanged();
                this.OnPropertyChanged("SessionDateTimeStart");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _SessionDateTimeStart;
        partial void OnSessionDateTimeStartChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnSessionDateTimeStartChanged();
        /// <summary>
        /// There are no comments for Property SessionDateTimeEnd in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> SessionDateTimeEnd
        {
            get
            {
                return this._SessionDateTimeEnd;
            }
            set
            {
                this.OnSessionDateTimeEndChanging(value);
                this._SessionDateTimeEnd = value;
                this.OnSessionDateTimeEndChanged();
                this.OnPropertyChanged("SessionDateTimeEnd");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _SessionDateTimeEnd;
        partial void OnSessionDateTimeEndChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnSessionDateTimeEndChanged();
        /// <summary>
        /// There are no comments for Property SessionCategory in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SessionCategory
        {
            get
            {
                return this._SessionCategory;
            }
            set
            {
                this.OnSessionCategoryChanging(value);
                this._SessionCategory = value;
                this.OnSessionCategoryChanged();
                this.OnPropertyChanged("SessionCategory");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SessionCategory;
        partial void OnSessionCategoryChanging(string value);
        partial void OnSessionCategoryChanged();
        /// <summary>
        /// There are no comments for Property SessionTrack in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SessionTrack
        {
            get
            {
                return this._SessionTrack;
            }
            set
            {
                this.OnSessionTrackChanging(value);
                this._SessionTrack = value;
                this.OnSessionTrackChanged();
                this.OnPropertyChanged("SessionTrack");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SessionTrack;
        partial void OnSessionTrackChanging(string value);
        partial void OnSessionTrackChanged();
        /// <summary>
        /// There are no comments for Property SessionCode in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SessionCode
        {
            get
            {
                return this._SessionCode;
            }
            set
            {
                this.OnSessionCodeChanging(value);
                this._SessionCode = value;
                this.OnSessionCodeChanged();
                this.OnPropertyChanged("SessionCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SessionCode;
        partial void OnSessionCodeChanging(string value);
        partial void OnSessionCodeChanged();
        /// <summary>
        /// There are no comments for Property SessionRoom in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SessionRoom
        {
            get
            {
                return this._SessionRoom;
            }
            set
            {
                this.OnSessionRoomChanging(value);
                this._SessionRoom = value;
                this.OnSessionRoomChanged();
                this.OnPropertyChanged("SessionRoom");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SessionRoom;
        partial void OnSessionRoomChanging(string value);
        partial void OnSessionRoomChanged();
        /// <summary>
        /// There are no comments for Property SessionPrerequisites in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SessionPrerequisites
        {
            get
            {
                return this._SessionPrerequisites;
            }
            set
            {
                this.OnSessionPrerequisitesChanging(value);
                this._SessionPrerequisites = value;
                this.OnSessionPrerequisitesChanged();
                this.OnPropertyChanged("SessionPrerequisites");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SessionPrerequisites;
        partial void OnSessionPrerequisitesChanging(string value);
        partial void OnSessionPrerequisitesChanged();
        /// <summary>
        /// There are no comments for Property SessionLevel in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SessionLevel
        {
            get
            {
                return this._SessionLevel;
            }
            set
            {
                this.OnSessionLevelChanging(value);
                this._SessionLevel = value;
                this.OnSessionLevelChanged();
                this.OnPropertyChanged("SessionLevel");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SessionLevel;
        partial void OnSessionLevelChanging(string value);
        partial void OnSessionLevelChanged();
        /// <summary>
        /// There are no comments for Property SessionURL in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SessionURL
        {
            get
            {
                return this._SessionURL;
            }
            set
            {
                this.OnSessionURLChanging(value);
                this._SessionURL = value;
                this.OnSessionURLChanged();
                this.OnPropertyChanged("SessionURL");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SessionURL;
        partial void OnSessionURLChanging(string value);
        partial void OnSessionURLChanged();
        /// <summary>
        /// There are no comments for Property SessionEvalURL in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SessionEvalURL
        {
            get
            {
                return this._SessionEvalURL;
            }
            set
            {
                this.OnSessionEvalURLChanging(value);
                this._SessionEvalURL = value;
                this.OnSessionEvalURLChanged();
                this.OnPropertyChanged("SessionEvalURL");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SessionEvalURL;
        partial void OnSessionEvalURLChanging(string value);
        partial void OnSessionEvalURLChanged();
        /// <summary>
        /// There are no comments for PASS_OData_Orator_Event in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Event PASS_OData_Orator_Event
        {
            get
            {
                return this._PASS_OData_Orator_Event;
            }
            set
            {
                this._PASS_OData_Orator_Event = value;
                this.OnPropertyChanged("PASS_OData_Orator_Event");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Event _PASS_OData_Orator_Event;
        /// <summary>
        /// There are no comments for PASS_OData_Orator_SessionSpeaker in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SessionSpeaker> PASS_OData_Orator_SessionSpeaker
        {
            get
            {
                return this._PASS_OData_Orator_SessionSpeaker;
            }
            set
            {
                this._PASS_OData_Orator_SessionSpeaker = value;
                this.OnPropertyChanged("PASS_OData_Orator_SessionSpeaker");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SessionSpeaker> _PASS_OData_Orator_SessionSpeaker = new global::System.Data.Services.Client.DataServiceCollection<SessionSpeaker>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for PASS_OData_Orator_SessionFile in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SessionFile> PASS_OData_Orator_SessionFile
        {
            get
            {
                return this._PASS_OData_Orator_SessionFile;
            }
            set
            {
                this._PASS_OData_Orator_SessionFile = value;
                this.OnPropertyChanged("PASS_OData_Orator_SessionFile");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SessionFile> _PASS_OData_Orator_SessionFile = new global::System.Data.Services.Client.DataServiceCollection<SessionFile>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OratorModelNS.SessionSpeaker in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SpeakerID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SessionSpeakers")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SpeakerID")]
    public partial class SessionSpeaker : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SessionSpeaker object.
        /// </summary>
        /// <param name="eventID">Initial value of EventID.</param>
        /// <param name="sessionID">Initial value of SessionID.</param>
        /// <param name="speakerID">Initial value of SpeakerID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SessionSpeaker CreateSessionSpeaker(int eventID, int sessionID, int speakerID)
        {
            SessionSpeaker sessionSpeaker = new SessionSpeaker();
            sessionSpeaker.EventID = eventID;
            sessionSpeaker.SessionID = sessionID;
            sessionSpeaker.SpeakerID = speakerID;
            return sessionSpeaker;
        }
        /// <summary>
        /// There are no comments for Property EventID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int EventID
        {
            get
            {
                return this._EventID;
            }
            set
            {
                this.OnEventIDChanging(value);
                this._EventID = value;
                this.OnEventIDChanged();
                this.OnPropertyChanged("EventID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _EventID;
        partial void OnEventIDChanging(int value);
        partial void OnEventIDChanged();
        /// <summary>
        /// There are no comments for Property SessionID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SessionID
        {
            get
            {
                return this._SessionID;
            }
            set
            {
                this.OnSessionIDChanging(value);
                this._SessionID = value;
                this.OnSessionIDChanged();
                this.OnPropertyChanged("SessionID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SessionID;
        partial void OnSessionIDChanging(int value);
        partial void OnSessionIDChanged();
        /// <summary>
        /// There are no comments for Property SpeakerID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SpeakerID
        {
            get
            {
                return this._SpeakerID;
            }
            set
            {
                this.OnSpeakerIDChanging(value);
                this._SpeakerID = value;
                this.OnSpeakerIDChanged();
                this.OnPropertyChanged("SpeakerID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SpeakerID;
        partial void OnSpeakerIDChanging(int value);
        partial void OnSpeakerIDChanged();
        /// <summary>
        /// There are no comments for Property SpeakerName in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SpeakerName
        {
            get
            {
                return this._SpeakerName;
            }
            set
            {
                this.OnSpeakerNameChanging(value);
                this._SpeakerName = value;
                this.OnSpeakerNameChanged();
                this.OnPropertyChanged("SpeakerName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SpeakerName;
        partial void OnSpeakerNameChanging(string value);
        partial void OnSpeakerNameChanged();
        /// <summary>
        /// There are no comments for Property SpeakerURL in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SpeakerURL
        {
            get
            {
                return this._SpeakerURL;
            }
            set
            {
                this.OnSpeakerURLChanging(value);
                this._SpeakerURL = value;
                this.OnSpeakerURLChanged();
                this.OnPropertyChanged("SpeakerURL");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SpeakerURL;
        partial void OnSpeakerURLChanging(string value);
        partial void OnSpeakerURLChanged();
        /// <summary>
        /// There are no comments for Property SpeakerImageURL in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SpeakerImageURL
        {
            get
            {
                return this._SpeakerImageURL;
            }
            set
            {
                this.OnSpeakerImageURLChanging(value);
                this._SpeakerImageURL = value;
                this.OnSpeakerImageURLChanged();
                this.OnPropertyChanged("SpeakerImageURL");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SpeakerImageURL;
        partial void OnSpeakerImageURLChanging(string value);
        partial void OnSpeakerImageURLChanged();
        /// <summary>
        /// There are no comments for Property SpeakerDescription in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SpeakerDescription
        {
            get
            {
                return this._SpeakerDescription;
            }
            set
            {
                this.OnSpeakerDescriptionChanging(value);
                this._SpeakerDescription = value;
                this.OnSpeakerDescriptionChanged();
                this.OnPropertyChanged("SpeakerDescription");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SpeakerDescription;
        partial void OnSpeakerDescriptionChanging(string value);
        partial void OnSpeakerDescriptionChanged();
        /// <summary>
        /// There are no comments for PASS_OData_Orator_Event in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Event PASS_OData_Orator_Event
        {
            get
            {
                return this._PASS_OData_Orator_Event;
            }
            set
            {
                this._PASS_OData_Orator_Event = value;
                this.OnPropertyChanged("PASS_OData_Orator_Event");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Event _PASS_OData_Orator_Event;
        /// <summary>
        /// There are no comments for PASS_OData_Orator_Session in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Session PASS_OData_Orator_Session
        {
            get
            {
                return this._PASS_OData_Orator_Session;
            }
            set
            {
                this._PASS_OData_Orator_Session = value;
                this.OnPropertyChanged("PASS_OData_Orator_Session");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Session _PASS_OData_Orator_Session;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OratorModelNS.SessionFile in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EventID
    /// SessionID
    /// FileID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SessionFiles")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("EventID", "SessionID", "FileID")]
    public partial class SessionFile : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SessionFile object.
        /// </summary>
        /// <param name="eventID">Initial value of EventID.</param>
        /// <param name="sessionID">Initial value of SessionID.</param>
        /// <param name="fileID">Initial value of FileID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SessionFile CreateSessionFile(int eventID, int sessionID, int fileID)
        {
            SessionFile sessionFile = new SessionFile();
            sessionFile.EventID = eventID;
            sessionFile.SessionID = sessionID;
            sessionFile.FileID = fileID;
            return sessionFile;
        }
        /// <summary>
        /// There are no comments for Property EventID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int EventID
        {
            get
            {
                return this._EventID;
            }
            set
            {
                this.OnEventIDChanging(value);
                this._EventID = value;
                this.OnEventIDChanged();
                this.OnPropertyChanged("EventID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _EventID;
        partial void OnEventIDChanging(int value);
        partial void OnEventIDChanged();
        /// <summary>
        /// There are no comments for Property SessionID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SessionID
        {
            get
            {
                return this._SessionID;
            }
            set
            {
                this.OnSessionIDChanging(value);
                this._SessionID = value;
                this.OnSessionIDChanged();
                this.OnPropertyChanged("SessionID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SessionID;
        partial void OnSessionIDChanging(int value);
        partial void OnSessionIDChanged();
        /// <summary>
        /// There are no comments for Property FileID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int FileID
        {
            get
            {
                return this._FileID;
            }
            set
            {
                this.OnFileIDChanging(value);
                this._FileID = value;
                this.OnFileIDChanged();
                this.OnPropertyChanged("FileID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _FileID;
        partial void OnFileIDChanging(int value);
        partial void OnFileIDChanged();
        /// <summary>
        /// There are no comments for Property FileName in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this.OnFileNameChanging(value);
                this._FileName = value;
                this.OnFileNameChanged();
                this.OnPropertyChanged("FileName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FileName;
        partial void OnFileNameChanging(string value);
        partial void OnFileNameChanged();
        /// <summary>
        /// There are no comments for Property FileURL in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FileURL
        {
            get
            {
                return this._FileURL;
            }
            set
            {
                this.OnFileURLChanging(value);
                this._FileURL = value;
                this.OnFileURLChanged();
                this.OnPropertyChanged("FileURL");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FileURL;
        partial void OnFileURLChanging(string value);
        partial void OnFileURLChanged();
        /// <summary>
        /// There are no comments for PASS_OData_Orator_Event in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Event PASS_OData_Orator_Event
        {
            get
            {
                return this._PASS_OData_Orator_Event;
            }
            set
            {
                this._PASS_OData_Orator_Event = value;
                this.OnPropertyChanged("PASS_OData_Orator_Event");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Event _PASS_OData_Orator_Event;
        /// <summary>
        /// There are no comments for PASS_OData_Orator_Session in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Session PASS_OData_Orator_Session
        {
            get
            {
                return this._PASS_OData_Orator_Session;
            }
            set
            {
                this._PASS_OData_Orator_Session = value;
                this.OnPropertyChanged("PASS_OData_Orator_Session");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Session _PASS_OData_Orator_Session;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
