'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.237
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'Original file name:
'Generation date: 9/24/2011 8:29:08 AM
Namespace Netflix
    '''<summary>
    '''There are no comments for NetflixCatalog in the schema.
    '''</summary>
    <Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true)>  _
    Partial Public Class NetflixCatalog
        Inherits Global.System.Data.Services.Client.DataServiceContext
        '''<summary>
        '''Initialize a new NetflixCatalog object.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub New(ByVal serviceRoot As Global.System.Uri)
            MyBase.New(serviceRoot)
            Me.ResolveName = AddressOf Me.ResolveNameFromType
            Me.ResolveType = AddressOf Me.ResolveTypeFromName
            Me.OnContextCreated
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private Shared ROOTNAMESPACE As String = GetType(Netflix.NetflixCatalog).Namespace.Remove(GetType(Netflix.NetflixCatalog).Namespace.LastIndexOf("Netflix"))
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveTypeFromName(ByVal typeName As String) As Global.System.Type
            If typeName.StartsWith("NetflixCatalog.Model", Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return Me.GetType.Assembly.GetType(String.Concat(String.Concat(ROOTNAMESPACE, "Netflix"), typeName.Substring(20)), false)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
            If clientType.Namespace.Equals(String.Concat(ROOTNAMESPACE, "Netflix"), Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return String.Concat("NetflixCatalog.Model.", clientType.Name)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''There are no comments for Genres in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Genres() As Global.System.Data.Services.Client.DataServiceQuery(Of Genre)
            Get
                If (Me._Genres Is Nothing) Then
                    Me._Genres = MyBase.CreateQuery(Of Genre)("Genres")
                End If
                Return Me._Genres
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Genres As Global.System.Data.Services.Client.DataServiceQuery(Of Genre)
        '''<summary>
        '''There are no comments for Languages in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Languages() As Global.System.Data.Services.Client.DataServiceQuery(Of Language)
            Get
                If (Me._Languages Is Nothing) Then
                    Me._Languages = MyBase.CreateQuery(Of Language)("Languages")
                End If
                Return Me._Languages
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Languages As Global.System.Data.Services.Client.DataServiceQuery(Of Language)
        '''<summary>
        '''There are no comments for People in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property People() As Global.System.Data.Services.Client.DataServiceQuery(Of Person)
            Get
                If (Me._People Is Nothing) Then
                    Me._People = MyBase.CreateQuery(Of Person)("People")
                End If
                Return Me._People
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _People As Global.System.Data.Services.Client.DataServiceQuery(Of Person)
        '''<summary>
        '''There are no comments for TitleAudioFormats in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property TitleAudioFormats() As Global.System.Data.Services.Client.DataServiceQuery(Of TitleAudioFormat)
            Get
                If (Me._TitleAudioFormats Is Nothing) Then
                    Me._TitleAudioFormats = MyBase.CreateQuery(Of TitleAudioFormat)("TitleAudioFormats")
                End If
                Return Me._TitleAudioFormats
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TitleAudioFormats As Global.System.Data.Services.Client.DataServiceQuery(Of TitleAudioFormat)
        '''<summary>
        '''There are no comments for TitleAwards in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property TitleAwards() As Global.System.Data.Services.Client.DataServiceQuery(Of TitleAward)
            Get
                If (Me._TitleAwards Is Nothing) Then
                    Me._TitleAwards = MyBase.CreateQuery(Of TitleAward)("TitleAwards")
                End If
                Return Me._TitleAwards
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TitleAwards As Global.System.Data.Services.Client.DataServiceQuery(Of TitleAward)
        '''<summary>
        '''There are no comments for Titles in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Titles() As Global.System.Data.Services.Client.DataServiceQuery(Of Title)
            Get
                If (Me._Titles Is Nothing) Then
                    Me._Titles = MyBase.CreateQuery(Of Title)("Titles")
                End If
                Return Me._Titles
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Titles As Global.System.Data.Services.Client.DataServiceQuery(Of Title)
        '''<summary>
        '''There are no comments for TitleScreenFormats in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property TitleScreenFormats() As Global.System.Data.Services.Client.DataServiceQuery(Of TitleScreenFormat)
            Get
                If (Me._TitleScreenFormats Is Nothing) Then
                    Me._TitleScreenFormats = MyBase.CreateQuery(Of TitleScreenFormat)("TitleScreenFormats")
                End If
                Return Me._TitleScreenFormats
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TitleScreenFormats As Global.System.Data.Services.Client.DataServiceQuery(Of TitleScreenFormat)
        '''<summary>
        '''There are no comments for Genres in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToGenres(ByVal genre As Genre)
            MyBase.AddObject("Genres", genre)
        End Sub
        '''<summary>
        '''There are no comments for Languages in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToLanguages(ByVal language As Language)
            MyBase.AddObject("Languages", language)
        End Sub
        '''<summary>
        '''There are no comments for People in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToPeople(ByVal person As Person)
            MyBase.AddObject("People", person)
        End Sub
        '''<summary>
        '''There are no comments for TitleAudioFormats in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToTitleAudioFormats(ByVal titleAudioFormat As TitleAudioFormat)
            MyBase.AddObject("TitleAudioFormats", titleAudioFormat)
        End Sub
        '''<summary>
        '''There are no comments for TitleAwards in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToTitleAwards(ByVal titleAward As TitleAward)
            MyBase.AddObject("TitleAwards", titleAward)
        End Sub
        '''<summary>
        '''There are no comments for Titles in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToTitles(ByVal title As Title)
            MyBase.AddObject("Titles", title)
        End Sub
        '''<summary>
        '''There are no comments for TitleScreenFormats in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToTitleScreenFormats(ByVal titleScreenFormat As TitleScreenFormat)
            MyBase.AddObject("TitleScreenFormats", titleScreenFormat)
        End Sub
    End Class
    '''<summary>
    '''There are no comments for NetflixCatalog.Model.Genre in the schema.
    '''</summary>
    '''<KeyProperties>
    '''Name
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Genres"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Data.Services.Common.EntityPropertyMappingAttribute("Name", System.Data.Services.Common.SyndicationItemProperty.Title, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("Name")>  _
    Partial Public Class Genre
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Genre object.
        '''</summary>
        '''<param name="name">Initial value of Name.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateGenre(ByVal name As String) As Genre
            Dim genre As Genre = New Genre()
            genre.Name = name
            Return genre
        End Function
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                Me._Name = value
                Me.OnNameChanged
                Me.OnPropertyChanged("Name")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Titles in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Titles() As Global.System.Data.Services.Client.DataServiceCollection(Of Title)
            Get
                Return Me._Titles
            End Get
            Set
                Me._Titles = value
                Me.OnPropertyChanged("Titles")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Titles As Global.System.Data.Services.Client.DataServiceCollection(Of Title) = New Global.System.Data.Services.Client.DataServiceCollection(Of Title)(Nothing, System.Data.Services.Client.TrackingMode.None)
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for NetflixCatalog.Model.Language in the schema.
    '''</summary>
    '''<KeyProperties>
    '''Name
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Languages"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Data.Services.Common.EntityPropertyMappingAttribute("Name", System.Data.Services.Common.SyndicationItemProperty.Title, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("Name")>  _
    Partial Public Class Language
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Language object.
        '''</summary>
        '''<param name="name">Initial value of Name.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateLanguage(ByVal name As String) As Language
            Dim language As Language = New Language()
            language.Name = name
            Return language
        End Function
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                Me._Name = value
                Me.OnNameChanged
                Me.OnPropertyChanged("Name")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Titles in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Titles() As Global.System.Data.Services.Client.DataServiceCollection(Of Title)
            Get
                Return Me._Titles
            End Get
            Set
                Me._Titles = value
                Me.OnPropertyChanged("Titles")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Titles As Global.System.Data.Services.Client.DataServiceCollection(Of Title) = New Global.System.Data.Services.Client.DataServiceCollection(Of Title)(Nothing, System.Data.Services.Client.TrackingMode.None)
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for NetflixCatalog.Model.Person in the schema.
    '''</summary>
    '''<KeyProperties>
    '''Id
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("People"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Data.Services.Common.EntityPropertyMappingAttribute("Name", System.Data.Services.Common.SyndicationItemProperty.Title, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("Id")>  _
    Partial Public Class Person
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Person object.
        '''</summary>
        '''<param name="ID">Initial value of Id.</param>
        '''<param name="name">Initial value of Name.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreatePerson(ByVal ID As Integer, ByVal name As String) As Person
            Dim person As Person = New Person()
            person.Id = ID
            person.Name = name
            Return person
        End Function
        '''<summary>
        '''There are no comments for Property Id in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Id() As Integer
            Get
                Return Me._Id
            End Get
            Set
                Me.OnIdChanging(value)
                Me._Id = value
                Me.OnIdChanged
                Me.OnPropertyChanged("Id")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Id As Integer
        Partial Private Sub OnIdChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnIdChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                Me._Name = value
                Me.OnNameChanged
                Me.OnPropertyChanged("Name")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Awards in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Awards() As Global.System.Data.Services.Client.DataServiceCollection(Of TitleAward)
            Get
                Return Me._Awards
            End Get
            Set
                Me._Awards = value
                Me.OnPropertyChanged("Awards")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Awards As Global.System.Data.Services.Client.DataServiceCollection(Of TitleAward) = New Global.System.Data.Services.Client.DataServiceCollection(Of TitleAward)(Nothing, System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for TitlesActedIn in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property TitlesActedIn() As Global.System.Data.Services.Client.DataServiceCollection(Of Title)
            Get
                Return Me._TitlesActedIn
            End Get
            Set
                Me._TitlesActedIn = value
                Me.OnPropertyChanged("TitlesActedIn")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TitlesActedIn As Global.System.Data.Services.Client.DataServiceCollection(Of Title) = New Global.System.Data.Services.Client.DataServiceCollection(Of Title)(Nothing, System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for TitlesDirected in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property TitlesDirected() As Global.System.Data.Services.Client.DataServiceCollection(Of Title)
            Get
                Return Me._TitlesDirected
            End Get
            Set
                Me._TitlesDirected = value
                Me.OnPropertyChanged("TitlesDirected")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TitlesDirected As Global.System.Data.Services.Client.DataServiceCollection(Of Title) = New Global.System.Data.Services.Client.DataServiceCollection(Of Title)(Nothing, System.Data.Services.Client.TrackingMode.None)
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for NetflixCatalog.Model.TitleAudioFormat in the schema.
    '''</summary>
    '''<KeyProperties>
    '''TitleId
    '''DeliveryFormat
    '''Language
    '''Format
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("TitleAudioFormats"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("TitleId", "DeliveryFormat", "Language", "Format")>  _
    Partial Public Class TitleAudioFormat
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new TitleAudioFormat object.
        '''</summary>
        '''<param name="titleId">Initial value of TitleId.</param>
        '''<param name="deliveryFormat">Initial value of DeliveryFormat.</param>
        '''<param name="language">Initial value of Language.</param>
        '''<param name="format">Initial value of Format.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateTitleAudioFormat(ByVal titleId As String, ByVal deliveryFormat As String, ByVal language As String, ByVal format As String) As TitleAudioFormat
            Dim titleAudioFormat As TitleAudioFormat = New TitleAudioFormat()
            titleAudioFormat.TitleId = titleId
            titleAudioFormat.DeliveryFormat = deliveryFormat
            titleAudioFormat.Language = language
            titleAudioFormat.Format = format
            Return titleAudioFormat
        End Function
        '''<summary>
        '''There are no comments for Property TitleId in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property TitleId() As String
            Get
                Return Me._TitleId
            End Get
            Set
                Me.OnTitleIdChanging(value)
                Me._TitleId = value
                Me.OnTitleIdChanged
                Me.OnPropertyChanged("TitleId")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TitleId As String
        Partial Private Sub OnTitleIdChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnTitleIdChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property DeliveryFormat in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property DeliveryFormat() As String
            Get
                Return Me._DeliveryFormat
            End Get
            Set
                Me.OnDeliveryFormatChanging(value)
                Me._DeliveryFormat = value
                Me.OnDeliveryFormatChanged
                Me.OnPropertyChanged("DeliveryFormat")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DeliveryFormat As String
        Partial Private Sub OnDeliveryFormatChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnDeliveryFormatChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Language in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Language() As String
            Get
                Return Me._Language
            End Get
            Set
                Me.OnLanguageChanging(value)
                Me._Language = value
                Me.OnLanguageChanged
                Me.OnPropertyChanged("Language")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Language As String
        Partial Private Sub OnLanguageChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnLanguageChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Format in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Format() As String
            Get
                Return Me._Format
            End Get
            Set
                Me.OnFormatChanging(value)
                Me._Format = value
                Me.OnFormatChanged
                Me.OnPropertyChanged("Format")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Format As String
        Partial Private Sub OnFormatChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnFormatChanged()
        End Sub
        '''<summary>
        '''There are no comments for Title in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Title() As Title
            Get
                Return Me._Title
            End Get
            Set
                Me._Title = value
                Me.OnPropertyChanged("Title")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Title As Title
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for NetflixCatalog.Model.TitleAward in the schema.
    '''</summary>
    '''<KeyProperties>
    '''Id
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("TitleAwards"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("Id")>  _
    Partial Public Class TitleAward
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new TitleAward object.
        '''</summary>
        '''<param name="ID">Initial value of Id.</param>
        '''<param name="type">Initial value of Type.</param>
        '''<param name="category">Initial value of Category.</param>
        '''<param name="won">Initial value of Won.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateTitleAward(ByVal ID As Global.System.Guid, ByVal type As String, ByVal category As String, ByVal won As Boolean) As TitleAward
            Dim titleAward As TitleAward = New TitleAward()
            titleAward.Id = ID
            titleAward.Type = type
            titleAward.Category = category
            titleAward.Won = won
            Return titleAward
        End Function
        '''<summary>
        '''There are no comments for Property Id in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Id() As Global.System.Guid
            Get
                Return Me._Id
            End Get
            Set
                Me.OnIdChanging(value)
                Me._Id = value
                Me.OnIdChanged
                Me.OnPropertyChanged("Id")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Id As Global.System.Guid
        Partial Private Sub OnIdChanging(ByVal value As Global.System.Guid)
        End Sub
        Partial Private Sub OnIdChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Type in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Type() As String
            Get
                Return Me._Type
            End Get
            Set
                Me.OnTypeChanging(value)
                Me._Type = value
                Me.OnTypeChanged
                Me.OnPropertyChanged("Type")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Type As String
        Partial Private Sub OnTypeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnTypeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Category in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Category() As String
            Get
                Return Me._Category
            End Get
            Set
                Me.OnCategoryChanging(value)
                Me._Category = value
                Me.OnCategoryChanged
                Me.OnPropertyChanged("Category")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Category As String
        Partial Private Sub OnCategoryChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCategoryChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Year in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Year() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Year
            End Get
            Set
                Me.OnYearChanging(value)
                Me._Year = value
                Me.OnYearChanged
                Me.OnPropertyChanged("Year")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Year As Global.System.Nullable(Of Integer)
        Partial Private Sub OnYearChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnYearChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Won in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Won() As Boolean
            Get
                Return Me._Won
            End Get
            Set
                Me.OnWonChanging(value)
                Me._Won = value
                Me.OnWonChanged
                Me.OnPropertyChanged("Won")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Won As Boolean
        Partial Private Sub OnWonChanging(ByVal value As Boolean)
        End Sub
        Partial Private Sub OnWonChanged()
        End Sub
        '''<summary>
        '''There are no comments for Title in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Title() As Title
            Get
                Return Me._Title
            End Get
            Set
                Me._Title = value
                Me.OnPropertyChanged("Title")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Title As Title
        '''<summary>
        '''There are no comments for Person in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Person() As Person
            Get
                Return Me._Person
            End Get
            Set
                Me._Person = value
                Me.OnPropertyChanged("Person")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Person As Person
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for ComplexType NetflixCatalog.Model.BoxArt in the schema.
    '''</summary>
    <Global.System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class BoxArt
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''There are no comments for Property SmallUrl in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property SmallUrl() As String
            Get
                Return Me._SmallUrl
            End Get
            Set
                Me.OnSmallUrlChanging(value)
                Me._SmallUrl = value
                Me.OnSmallUrlChanged
                Me.OnPropertyChanged("SmallUrl")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _SmallUrl As String
        Partial Private Sub OnSmallUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnSmallUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property MediumUrl in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property MediumUrl() As String
            Get
                Return Me._MediumUrl
            End Get
            Set
                Me.OnMediumUrlChanging(value)
                Me._MediumUrl = value
                Me.OnMediumUrlChanged
                Me.OnPropertyChanged("MediumUrl")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _MediumUrl As String
        Partial Private Sub OnMediumUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnMediumUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property LargeUrl in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property LargeUrl() As String
            Get
                Return Me._LargeUrl
            End Get
            Set
                Me.OnLargeUrlChanging(value)
                Me._LargeUrl = value
                Me.OnLargeUrlChanged
                Me.OnPropertyChanged("LargeUrl")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _LargeUrl As String
        Partial Private Sub OnLargeUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnLargeUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property HighDefinitionUrl in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property HighDefinitionUrl() As String
            Get
                Return Me._HighDefinitionUrl
            End Get
            Set
                Me.OnHighDefinitionUrlChanging(value)
                Me._HighDefinitionUrl = value
                Me.OnHighDefinitionUrlChanged
                Me.OnPropertyChanged("HighDefinitionUrl")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _HighDefinitionUrl As String
        Partial Private Sub OnHighDefinitionUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnHighDefinitionUrlChanged()
        End Sub
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for ComplexType NetflixCatalog.Model.InstantAvailability in the schema.
    '''</summary>
    <Global.System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class InstantAvailability
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new InstantAvailability object.
        '''</summary>
        '''<param name="available">Initial value of Available.</param>
        '''<param name="highDefinitionAvailable">Initial value of HighDefinitionAvailable.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateInstantAvailability(ByVal available As Boolean, ByVal highDefinitionAvailable As Boolean) As InstantAvailability
            Dim instantAvailability As InstantAvailability = New InstantAvailability()
            instantAvailability.Available = available
            instantAvailability.HighDefinitionAvailable = highDefinitionAvailable
            Return instantAvailability
        End Function
        '''<summary>
        '''There are no comments for Property Available in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Available() As Boolean
            Get
                Return Me._Available
            End Get
            Set
                Me.OnAvailableChanging(value)
                Me._Available = value
                Me.OnAvailableChanged
                Me.OnPropertyChanged("Available")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Available As Boolean
        Partial Private Sub OnAvailableChanging(ByVal value As Boolean)
        End Sub
        Partial Private Sub OnAvailableChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property AvailableFrom in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property AvailableFrom() As Global.System.Nullable(Of Date)
            Get
                Return Me._AvailableFrom
            End Get
            Set
                Me.OnAvailableFromChanging(value)
                Me._AvailableFrom = value
                Me.OnAvailableFromChanged
                Me.OnPropertyChanged("AvailableFrom")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _AvailableFrom As Global.System.Nullable(Of Date)
        Partial Private Sub OnAvailableFromChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnAvailableFromChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property AvailableTo in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property AvailableTo() As Global.System.Nullable(Of Date)
            Get
                Return Me._AvailableTo
            End Get
            Set
                Me.OnAvailableToChanging(value)
                Me._AvailableTo = value
                Me.OnAvailableToChanged
                Me.OnPropertyChanged("AvailableTo")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _AvailableTo As Global.System.Nullable(Of Date)
        Partial Private Sub OnAvailableToChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnAvailableToChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property HighDefinitionAvailable in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property HighDefinitionAvailable() As Boolean
            Get
                Return Me._HighDefinitionAvailable
            End Get
            Set
                Me.OnHighDefinitionAvailableChanging(value)
                Me._HighDefinitionAvailable = value
                Me.OnHighDefinitionAvailableChanged
                Me.OnPropertyChanged("HighDefinitionAvailable")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _HighDefinitionAvailable As Boolean
        Partial Private Sub OnHighDefinitionAvailableChanging(ByVal value As Boolean)
        End Sub
        Partial Private Sub OnHighDefinitionAvailableChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Runtime in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Runtime() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Runtime
            End Get
            Set
                Me.OnRuntimeChanging(value)
                Me._Runtime = value
                Me.OnRuntimeChanged
                Me.OnPropertyChanged("Runtime")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Runtime As Global.System.Nullable(Of Integer)
        Partial Private Sub OnRuntimeChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnRuntimeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Rating in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Rating() As String
            Get
                Return Me._Rating
            End Get
            Set
                Me.OnRatingChanging(value)
                Me._Rating = value
                Me.OnRatingChanged
                Me.OnPropertyChanged("Rating")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Rating As String
        Partial Private Sub OnRatingChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnRatingChanged()
        End Sub
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for ComplexType NetflixCatalog.Model.DeliveryFormatAvailability in the schema.
    '''</summary>
    <Global.System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class DeliveryFormatAvailability
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new DeliveryFormatAvailability object.
        '''</summary>
        '''<param name="available">Initial value of Available.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateDeliveryFormatAvailability(ByVal available As Boolean) As DeliveryFormatAvailability
            Dim deliveryFormatAvailability As DeliveryFormatAvailability = New DeliveryFormatAvailability()
            deliveryFormatAvailability.Available = available
            Return deliveryFormatAvailability
        End Function
        '''<summary>
        '''There are no comments for Property Available in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Available() As Boolean
            Get
                Return Me._Available
            End Get
            Set
                Me.OnAvailableChanging(value)
                Me._Available = value
                Me.OnAvailableChanged
                Me.OnPropertyChanged("Available")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Available As Boolean
        Partial Private Sub OnAvailableChanging(ByVal value As Boolean)
        End Sub
        Partial Private Sub OnAvailableChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property AvailableFrom in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property AvailableFrom() As Global.System.Nullable(Of Date)
            Get
                Return Me._AvailableFrom
            End Get
            Set
                Me.OnAvailableFromChanging(value)
                Me._AvailableFrom = value
                Me.OnAvailableFromChanged
                Me.OnPropertyChanged("AvailableFrom")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _AvailableFrom As Global.System.Nullable(Of Date)
        Partial Private Sub OnAvailableFromChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnAvailableFromChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property AvailableTo in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property AvailableTo() As Global.System.Nullable(Of Date)
            Get
                Return Me._AvailableTo
            End Get
            Set
                Me.OnAvailableToChanging(value)
                Me._AvailableTo = value
                Me.OnAvailableToChanged
                Me.OnPropertyChanged("AvailableTo")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _AvailableTo As Global.System.Nullable(Of Date)
        Partial Private Sub OnAvailableToChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnAvailableToChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Runtime in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Runtime() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Runtime
            End Get
            Set
                Me.OnRuntimeChanging(value)
                Me._Runtime = value
                Me.OnRuntimeChanged
                Me.OnPropertyChanged("Runtime")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Runtime As Global.System.Nullable(Of Integer)
        Partial Private Sub OnRuntimeChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnRuntimeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Rating in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Rating() As String
            Get
                Return Me._Rating
            End Get
            Set
                Me.OnRatingChanging(value)
                Me._Rating = value
                Me.OnRatingChanged
                Me.OnPropertyChanged("Rating")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Rating As String
        Partial Private Sub OnRatingChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnRatingChanged()
        End Sub
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for NetflixCatalog.Model.Title in the schema.
    '''</summary>
    '''<KeyProperties>
    '''Id
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Titles"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Data.Services.Common.EntityPropertyMappingAttribute("Synopsis", System.Data.Services.Common.SyndicationItemProperty.Summary, System.Data.Services.Common.SyndicationTextContentKind.Html, true),  _
     Global.System.Data.Services.Common.EntityPropertyMappingAttribute("DateModified", System.Data.Services.Common.SyndicationItemProperty.Updated, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, false),  _
     Global.System.Data.Services.Common.EntityPropertyMappingAttribute("Name", System.Data.Services.Common.SyndicationItemProperty.Title, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true),  _
     Global.System.Data.Services.Common.HasStreamAttribute(),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("Id")>  _
    Partial Public Class Title
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Title object.
        '''</summary>
        '''<param name="ID">Initial value of Id.</param>
        '''<param name="dateModified">Initial value of DateModified.</param>
        '''<param name="type">Initial value of Type.</param>
        '''<param name="boxArt">Initial value of BoxArt.</param>
        '''<param name="shortName">Initial value of ShortName.</param>
        '''<param name="name">Initial value of Name.</param>
        '''<param name="instant">Initial value of Instant.</param>
        '''<param name="dvd">Initial value of Dvd.</param>
        '''<param name="bluRay">Initial value of BluRay.</param>
        '''<param name="tinyUrl">Initial value of TinyUrl.</param>
        '''<param name="netflixApiId">Initial value of NetflixApiId.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateTitle(ByVal ID As String, ByVal dateModified As Date, ByVal type As String, ByVal boxArt As BoxArt, ByVal shortName As String, ByVal name As String, ByVal instant As InstantAvailability, ByVal dvd As DeliveryFormatAvailability, ByVal bluRay As DeliveryFormatAvailability, ByVal tinyUrl As String, ByVal netflixApiId As String) As Title
            Dim title As Title = New Title()
            title.Id = ID
            title.DateModified = dateModified
            title.Type = type
            If (boxArt Is Nothing) Then
                Throw New Global.System.ArgumentNullException("boxArt")
            End If
            title.BoxArt = boxArt
            title.ShortName = shortName
            title.Name = name
            If (instant Is Nothing) Then
                Throw New Global.System.ArgumentNullException("instant")
            End If
            title.Instant = instant
            If (dvd Is Nothing) Then
                Throw New Global.System.ArgumentNullException("dvd")
            End If
            title.Dvd = dvd
            If (bluRay Is Nothing) Then
                Throw New Global.System.ArgumentNullException("bluRay")
            End If
            title.BluRay = bluRay
            title.TinyUrl = tinyUrl
            title.NetflixApiId = netflixApiId
            Return title
        End Function
        '''<summary>
        '''There are no comments for Property Id in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Id() As String
            Get
                Return Me._Id
            End Get
            Set
                Me.OnIdChanging(value)
                Me._Id = value
                Me.OnIdChanged
                Me.OnPropertyChanged("Id")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Id As String
        Partial Private Sub OnIdChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnIdChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Synopsis in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Synopsis() As String
            Get
                Return Me._Synopsis
            End Get
            Set
                Me.OnSynopsisChanging(value)
                Me._Synopsis = value
                Me.OnSynopsisChanged
                Me.OnPropertyChanged("Synopsis")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Synopsis As String
        Partial Private Sub OnSynopsisChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnSynopsisChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ShortSynopsis in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShortSynopsis() As String
            Get
                Return Me._ShortSynopsis
            End Get
            Set
                Me.OnShortSynopsisChanging(value)
                Me._ShortSynopsis = value
                Me.OnShortSynopsisChanged
                Me.OnPropertyChanged("ShortSynopsis")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShortSynopsis As String
        Partial Private Sub OnShortSynopsisChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnShortSynopsisChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property AverageRating in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property AverageRating() As Global.System.Nullable(Of Double)
            Get
                Return Me._AverageRating
            End Get
            Set
                Me.OnAverageRatingChanging(value)
                Me._AverageRating = value
                Me.OnAverageRatingChanged
                Me.OnPropertyChanged("AverageRating")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _AverageRating As Global.System.Nullable(Of Double)
        Partial Private Sub OnAverageRatingChanging(ByVal value As Global.System.Nullable(Of Double))
        End Sub
        Partial Private Sub OnAverageRatingChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ReleaseYear in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ReleaseYear() As Global.System.Nullable(Of Integer)
            Get
                Return Me._ReleaseYear
            End Get
            Set
                Me.OnReleaseYearChanging(value)
                Me._ReleaseYear = value
                Me.OnReleaseYearChanged
                Me.OnPropertyChanged("ReleaseYear")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ReleaseYear As Global.System.Nullable(Of Integer)
        Partial Private Sub OnReleaseYearChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnReleaseYearChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Url in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Url() As String
            Get
                Return Me._Url
            End Get
            Set
                Me.OnUrlChanging(value)
                Me._Url = value
                Me.OnUrlChanged
                Me.OnPropertyChanged("Url")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Url As String
        Partial Private Sub OnUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Runtime in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Runtime() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Runtime
            End Get
            Set
                Me.OnRuntimeChanging(value)
                Me._Runtime = value
                Me.OnRuntimeChanged
                Me.OnPropertyChanged("Runtime")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Runtime As Global.System.Nullable(Of Integer)
        Partial Private Sub OnRuntimeChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnRuntimeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Rating in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Rating() As String
            Get
                Return Me._Rating
            End Get
            Set
                Me.OnRatingChanging(value)
                Me._Rating = value
                Me.OnRatingChanged
                Me.OnPropertyChanged("Rating")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Rating As String
        Partial Private Sub OnRatingChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnRatingChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property DateModified in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property DateModified() As Date
            Get
                Return Me._DateModified
            End Get
            Set
                Me.OnDateModifiedChanging(value)
                Me._DateModified = value
                Me.OnDateModifiedChanged
                Me.OnPropertyChanged("DateModified")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DateModified As Date
        Partial Private Sub OnDateModifiedChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnDateModifiedChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Type in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Type() As String
            Get
                Return Me._Type
            End Get
            Set
                Me.OnTypeChanging(value)
                Me._Type = value
                Me.OnTypeChanged
                Me.OnPropertyChanged("Type")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Type As String
        Partial Private Sub OnTypeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnTypeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property BoxArt in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property BoxArt() As BoxArt
            Get
                If ((Me._BoxArt Is Nothing)  _
                            AndAlso (Me._BoxArtInitialized <> true)) Then
                    Me._BoxArt = New BoxArt()
                    Me._BoxArtInitialized = true
                End If
                Return Me._BoxArt
            End Get
            Set
                Me.OnBoxArtChanging(value)
                Me._BoxArt = value
                Me._BoxArtInitialized = true
                Me.OnBoxArtChanged
                Me.OnPropertyChanged("BoxArt")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _BoxArt As BoxArt
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _BoxArtInitialized As Boolean
        Partial Private Sub OnBoxArtChanging(ByVal value As BoxArt)
        End Sub
        Partial Private Sub OnBoxArtChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ShortName in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShortName() As String
            Get
                Return Me._ShortName
            End Get
            Set
                Me.OnShortNameChanging(value)
                Me._ShortName = value
                Me.OnShortNameChanged
                Me.OnPropertyChanged("ShortName")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShortName As String
        Partial Private Sub OnShortNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnShortNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                Me._Name = value
                Me.OnNameChanged
                Me.OnPropertyChanged("Name")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Instant in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Instant() As InstantAvailability
            Get
                If ((Me._Instant Is Nothing)  _
                            AndAlso (Me._InstantInitialized <> true)) Then
                    Me._Instant = New InstantAvailability()
                    Me._InstantInitialized = true
                End If
                Return Me._Instant
            End Get
            Set
                Me.OnInstantChanging(value)
                Me._Instant = value
                Me._InstantInitialized = true
                Me.OnInstantChanged
                Me.OnPropertyChanged("Instant")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Instant As InstantAvailability
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _InstantInitialized As Boolean
        Partial Private Sub OnInstantChanging(ByVal value As InstantAvailability)
        End Sub
        Partial Private Sub OnInstantChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Dvd in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Dvd() As DeliveryFormatAvailability
            Get
                If ((Me._Dvd Is Nothing)  _
                            AndAlso (Me._DvdInitialized <> true)) Then
                    Me._Dvd = New DeliveryFormatAvailability()
                    Me._DvdInitialized = true
                End If
                Return Me._Dvd
            End Get
            Set
                Me.OnDvdChanging(value)
                Me._Dvd = value
                Me._DvdInitialized = true
                Me.OnDvdChanged
                Me.OnPropertyChanged("Dvd")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Dvd As DeliveryFormatAvailability
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DvdInitialized As Boolean
        Partial Private Sub OnDvdChanging(ByVal value As DeliveryFormatAvailability)
        End Sub
        Partial Private Sub OnDvdChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property BluRay in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property BluRay() As DeliveryFormatAvailability
            Get
                If ((Me._BluRay Is Nothing)  _
                            AndAlso (Me._BluRayInitialized <> true)) Then
                    Me._BluRay = New DeliveryFormatAvailability()
                    Me._BluRayInitialized = true
                End If
                Return Me._BluRay
            End Get
            Set
                Me.OnBluRayChanging(value)
                Me._BluRay = value
                Me._BluRayInitialized = true
                Me.OnBluRayChanged
                Me.OnPropertyChanged("BluRay")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _BluRay As DeliveryFormatAvailability
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _BluRayInitialized As Boolean
        Partial Private Sub OnBluRayChanging(ByVal value As DeliveryFormatAvailability)
        End Sub
        Partial Private Sub OnBluRayChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property TinyUrl in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property TinyUrl() As String
            Get
                Return Me._TinyUrl
            End Get
            Set
                Me.OnTinyUrlChanging(value)
                Me._TinyUrl = value
                Me.OnTinyUrlChanged
                Me.OnPropertyChanged("TinyUrl")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TinyUrl As String
        Partial Private Sub OnTinyUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnTinyUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property WebsiteUrl in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property WebsiteUrl() As String
            Get
                Return Me._WebsiteUrl
            End Get
            Set
                Me.OnWebsiteUrlChanging(value)
                Me._WebsiteUrl = value
                Me.OnWebsiteUrlChanged
                Me.OnPropertyChanged("WebsiteUrl")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _WebsiteUrl As String
        Partial Private Sub OnWebsiteUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnWebsiteUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property NetflixApiId in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property NetflixApiId() As String
            Get
                Return Me._NetflixApiId
            End Get
            Set
                Me.OnNetflixApiIdChanging(value)
                Me._NetflixApiId = value
                Me.OnNetflixApiIdChanged
                Me.OnPropertyChanged("NetflixApiId")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _NetflixApiId As String
        Partial Private Sub OnNetflixApiIdChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNetflixApiIdChanged()
        End Sub
        '''<summary>
        '''There are no comments for AudioFormats in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property AudioFormats() As Global.System.Data.Services.Client.DataServiceCollection(Of TitleAudioFormat)
            Get
                Return Me._AudioFormats
            End Get
            Set
                Me._AudioFormats = value
                Me.OnPropertyChanged("AudioFormats")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _AudioFormats As Global.System.Data.Services.Client.DataServiceCollection(Of TitleAudioFormat) = New Global.System.Data.Services.Client.DataServiceCollection(Of TitleAudioFormat)(Nothing, System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for Awards in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Awards() As Global.System.Data.Services.Client.DataServiceCollection(Of TitleAward)
            Get
                Return Me._Awards
            End Get
            Set
                Me._Awards = value
                Me.OnPropertyChanged("Awards")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Awards As Global.System.Data.Services.Client.DataServiceCollection(Of TitleAward) = New Global.System.Data.Services.Client.DataServiceCollection(Of TitleAward)(Nothing, System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for Disc in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Disc() As Title
            Get
                Return Me._Disc
            End Get
            Set
                Me._Disc = value
                Me.OnPropertyChanged("Disc")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Disc As Title
        '''<summary>
        '''There are no comments for Movie in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Movie() As Title
            Get
                Return Me._Movie
            End Get
            Set
                Me._Movie = value
                Me.OnPropertyChanged("Movie")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Movie As Title
        '''<summary>
        '''There are no comments for Season in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Season() As Title
            Get
                Return Me._Season
            End Get
            Set
                Me._Season = value
                Me.OnPropertyChanged("Season")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Season As Title
        '''<summary>
        '''There are no comments for Series in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Series() As Title
            Get
                Return Me._Series
            End Get
            Set
                Me._Series = value
                Me.OnPropertyChanged("Series")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Series As Title
        '''<summary>
        '''There are no comments for ScreenFormats in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ScreenFormats() As Global.System.Data.Services.Client.DataServiceCollection(Of TitleScreenFormat)
            Get
                Return Me._ScreenFormats
            End Get
            Set
                Me._ScreenFormats = value
                Me.OnPropertyChanged("ScreenFormats")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ScreenFormats As Global.System.Data.Services.Client.DataServiceCollection(Of TitleScreenFormat) = New Global.System.Data.Services.Client.DataServiceCollection(Of TitleScreenFormat)(Nothing, System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for Cast in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Cast() As Global.System.Data.Services.Client.DataServiceCollection(Of Person)
            Get
                Return Me._Cast
            End Get
            Set
                Me._Cast = value
                Me.OnPropertyChanged("Cast")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Cast As Global.System.Data.Services.Client.DataServiceCollection(Of Person) = New Global.System.Data.Services.Client.DataServiceCollection(Of Person)(Nothing, System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for Languages in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Languages() As Global.System.Data.Services.Client.DataServiceCollection(Of Language)
            Get
                Return Me._Languages
            End Get
            Set
                Me._Languages = value
                Me.OnPropertyChanged("Languages")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Languages As Global.System.Data.Services.Client.DataServiceCollection(Of Language) = New Global.System.Data.Services.Client.DataServiceCollection(Of Language)(Nothing, System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for Directors in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Directors() As Global.System.Data.Services.Client.DataServiceCollection(Of Person)
            Get
                Return Me._Directors
            End Get
            Set
                Me._Directors = value
                Me.OnPropertyChanged("Directors")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Directors As Global.System.Data.Services.Client.DataServiceCollection(Of Person) = New Global.System.Data.Services.Client.DataServiceCollection(Of Person)(Nothing, System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for Genres in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Genres() As Global.System.Data.Services.Client.DataServiceCollection(Of Genre)
            Get
                Return Me._Genres
            End Get
            Set
                Me._Genres = value
                Me.OnPropertyChanged("Genres")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Genres As Global.System.Data.Services.Client.DataServiceCollection(Of Genre) = New Global.System.Data.Services.Client.DataServiceCollection(Of Genre)(Nothing, System.Data.Services.Client.TrackingMode.None)
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for NetflixCatalog.Model.TitleScreenFormat in the schema.
    '''</summary>
    '''<KeyProperties>
    '''TitleId
    '''DeliveryFormat
    '''Format
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("TitleScreenFormats"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("TitleId", "DeliveryFormat", "Format")>  _
    Partial Public Class TitleScreenFormat
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new TitleScreenFormat object.
        '''</summary>
        '''<param name="titleId">Initial value of TitleId.</param>
        '''<param name="deliveryFormat">Initial value of DeliveryFormat.</param>
        '''<param name="format">Initial value of Format.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateTitleScreenFormat(ByVal titleId As String, ByVal deliveryFormat As String, ByVal format As String) As TitleScreenFormat
            Dim titleScreenFormat As TitleScreenFormat = New TitleScreenFormat()
            titleScreenFormat.TitleId = titleId
            titleScreenFormat.DeliveryFormat = deliveryFormat
            titleScreenFormat.Format = format
            Return titleScreenFormat
        End Function
        '''<summary>
        '''There are no comments for Property TitleId in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property TitleId() As String
            Get
                Return Me._TitleId
            End Get
            Set
                Me.OnTitleIdChanging(value)
                Me._TitleId = value
                Me.OnTitleIdChanged
                Me.OnPropertyChanged("TitleId")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _TitleId As String
        Partial Private Sub OnTitleIdChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnTitleIdChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property DeliveryFormat in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property DeliveryFormat() As String
            Get
                Return Me._DeliveryFormat
            End Get
            Set
                Me.OnDeliveryFormatChanging(value)
                Me._DeliveryFormat = value
                Me.OnDeliveryFormatChanged
                Me.OnPropertyChanged("DeliveryFormat")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DeliveryFormat As String
        Partial Private Sub OnDeliveryFormatChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnDeliveryFormatChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Format in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Format() As String
            Get
                Return Me._Format
            End Get
            Set
                Me.OnFormatChanging(value)
                Me._Format = value
                Me.OnFormatChanged
                Me.OnPropertyChanged("Format")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Format As String
        Partial Private Sub OnFormatChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnFormatChanged()
        End Sub
        '''<summary>
        '''There are no comments for Title in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Title() As Title
            Get
                Return Me._Title
            End Get
            Set
                Me._Title = value
                Me.OnPropertyChanged("Title")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Title As Title
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
End Namespace
